### ISSUE TITLE
Deploy to prod from master branch

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1234]
Environment `pipelinedashboard-prod`.

From Travis CI [docs](https://docs.travis-ci.com/user/deployment/firebase/#deploying-to-a-custom-project)

> To deploy to a different project than the one specified in the firebase.json, use the project key in your .travis.yml:

```yaml
deploy:
  provider: firebase
  token:
    secure: "YOUR ENCRYPTED token"
  project: "myapp-staging"
```

## To do

- [ ] Add another deploy section to the travis ci config for `master` branch
- [ ] Set project to `project: "pipelinedashboard-prod"`
- [ ] Move firebase credentials to CI envars #1154 

For example..

```yaml
deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: $FIREBASE_PROD_TOKEN
    project: "pipelinedashboard-prod"
    message: "Deploying v0.11.5-$TRAVIS_BUILD_NUMBER-ALPHA"
    on:
      branch: master
```
