### ISSUE TITLE
API validation on aws lambda with serverless `400` status code

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#258]

**Comment by eddiejaoude** [comment]
```yaml
functions:
  environmentCreate:
    handler: environments/create.create
    events:
      - http:
          path: environments
          method: post
          integration: lambda-proxy
```

```javascript
if (typeof data.description !== 'string' || !validator.isLength(data.description, {min: 3, max: 1024})) {
    return callback(null, {
         statusCode: 400,
         body: JSON.stringify({message: 'Validation Error: "description" is optional but a "string" must be between 3 and 1024'}),
     });
}
```
