### ISSUE TITLE
Example data for local development

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#594]
https://www.npmjs.com/package/serverless-dynamodb-local#seeding-sls-dynamodb-seed

```yml
dynamodb:
  start:
    seed: true
 
  seed:
    domain:
      sources:
        - table: domain-widgets
          sources: [./domainWidgets.json]
        - table: domain-fidgets
          sources: [./domainFidgets.json]
    test:
      sources:
        - table: users
          sources: [./fake-test-users.json]
        - table: subscriptions
          sources: [./fake-test-subscriptions.json]
```
