### ISSUE TITLE
Validation not using Config for Theme list

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#78]
### Issue is not injecting parameter config dependency into validator.

Discussion on Stackoverflow regarding issue http://stackoverflow.com/questions/28997723/symfony-custom-validator-not-loading-dependency 
### services.yml

``` yaml
dashboardhub_app_main.validator.constraints.theme:
    class: DashboardHub\Bundle\AppBundle\Validator\Constraints\ThemeValidator
    arguments: ["%dashboard_hub_app%"]
    tags:
        - { name: validator.constraint_validator, alias: theme.validator }
```
### ThemeValidator.php

``` php
<?php
namespace DashboardHub\Bundle\AppBundle\Validator\Constraints;

use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\ConstraintValidator;

class ThemeValidator extends ConstraintValidator
{

    protected $config;

    public function __construct(array $config)
    {
        $this->config = $config;
    }

    public function validatedBy()
    {
        return 'theme.validator';
    }

    public function validate($value, Constraint $constraint)
    {
        var_dump($this->config); exit;
    }
}
```
